#define NVS_PARTITION	     storage_partition
#define NVS_PARTITION_DEVICE FIXED_PARTITION_DEVICE(NVS_PARTITION)
#define NVS_PARTITION_OFFSET FIXED_PARTITION_OFFSET(NVS_PARTITION)

#define WIFI_SSID_STORAGE_INDEX 0
#define WIFI_SSID_MAX_LENGTH	32
#define WIFI_PSK_STORAGE_INDEX	1
#define WIFI_PSK_MAX_LENGTH	64

#define CONFIG_USER_EMAIL_STORAGE_INDEX 2
#define CONFIG_USER_EMAIL_MAX_LENGTH	32

#define CONFIG_FARMING_STR_STORAGE_INDEX 3
#define CONFIG_FARMING_STR_MAX_LENGTH	512

#define CONFIG_FARMING_STR_LENGHT_STORAGE_INDEX 4
#define CONFIG_FARMING_STR_LENGHT_MAX_LENGTH	4
